version: "3"
services:
  nginx:
    image: nginx
    build: services/nginx
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - inception_files:/var/www/inception
    restart: on-failure

  wordpress:
    image: wordpress
    build: services/wordpress
    ports:
      - "8080"
    networks:
      - inception_network
    volumes:
      - inception_files:/var/www/inception
    restart: on-failure
  mariadb:
    image: mariadb
    build: services/mariadb
    ports:
      - "3306"
    networks:
      - inception_network
    volumes:
      - inception_db:/var/lib/mysql
    
volumes:
  inception_files:
  inception_db:

networks:
  inception_network:
  